name: Release Package

on:
  push:
    branches:
      - master  # Trigger the release when pushing to the main branch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false  # Prevents GitHub from using the bot credentials

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build package (tsup)
        run: pnpm run build  # Make sure this step builds the dist folder  

      - name: Print package.json version before
        run: cat package.json | jq .version  

      - name: Configure Git User
        run: |
          git config --global user.name "sanjayc208"
          git config --global user.email "sanjayc208@gmail.com"

      - name: Run semantic-release
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_FOX_TOAST }}              # Your npm token stored in GitHub Secrets
          GH_TOKEN: ${{ secrets.GH_PAT }}  # GitHub token for release
      
      - name: Print package.json version after
        run: cat package.json | jq .version    
